#!/usr/bin/env bash
#
# Build the site and serve it from nginx on port 9090, bringing it back by
# itself after a reboot.
#
#   scripts/deploy.sh                 # build → publish → configure → reload → verify
#   scripts/deploy.sh --skip-build    # re-publish the existing dist/
#   scripts/deploy.sh --port 9091     # same, on another port
#
# Targets Ubuntu/Debian (apt, /etc/nginx/sites-available, systemd) and macOS
# (Homebrew, servers/, launchd). Everything is idempotent, and nginx is only
# ever reloaded, never restarted, so other sites it serves keep answering.

set -euo pipefail

# ---------------------------------------------------------------- settings --

PORT=9090
WEBROOT=""          # defaults per platform, see below
SITE_URL=""         # VITE_SITE_URL for the build; empty keeps .env's value
IN_PLACE=0          # serve dist/ where it lies instead of copying it out
SKIP_BUILD=0
NO_SERVICE=0        # configure nginx but leave systemd/launchd alone

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="$REPO_ROOT/deploy/nginx/ail-website.conf"
CONF_NAME="ail-website.conf"

# Stamped into every rendered config, so the script can recognise its own work
# wherever it ends up — including through a sites-enabled symlink.
GEN_MARKER="# Generated by scripts/deploy.sh"

# ----------------------------------------------------------------- output ---

say()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
ok()   { printf '    \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '    \033[33m!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
    # The header comment is the usage text; stop at the first line that is not one.
    awk 'NR > 1 { if ($0 !~ /^#/) exit; sub(/^# ?/, ""); print }' "${BASH_SOURCE[0]}"
    cat <<'USAGE'

Options
  --port N          port to listen on (default 9090)
  --webroot PATH    where the build is published (default /var/www/ail-website)
  --site-url URL    VITE_SITE_URL baked into the build's social tags
  --in-place        serve dist/ directly instead of copying it out
  --skip-build      reuse the existing dist/ (build it on another machine and copy it over)
  --no-service      write the config and reload, but do not enable the service
  -h, --help        this text
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        --port)       PORT="${2:?--port needs a value}"; shift 2 ;;
        --webroot)    WEBROOT="${2:?--webroot needs a value}"; shift 2 ;;
        --site-url)   SITE_URL="${2:?--site-url needs a value}"; shift 2 ;;
        --in-place)   IN_PLACE=1; shift ;;
        --skip-build) SKIP_BUILD=1; shift ;;
        --no-service) NO_SERVICE=1; shift ;;
        -h|--help)    usage; exit 0 ;;
        *)            die "unknown argument: $1 (try --help)" ;;
    esac
done

case "$PORT" in
    ''|*[!0-9]*) die "--port must be a number, got: $PORT" ;;
esac
[ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || die "--port out of range: $PORT"

# ---------------------------------------------------------------- platform --
# Everything that differs between the deploy target and the dev machine lives
# in this section; the steps below are written once.

OS="$(uname -s)"

IS_ROOT=0
if [ "$(id -u)" -eq 0 ]; then IS_ROOT=1; fi

HAVE_SUDO=0
if [ "$IS_ROOT" -eq 0 ] && command -v sudo >/dev/null 2>&1; then
    # Either sudo is already unlocked, or there is a terminal it can ask on.
    if sudo -n true >/dev/null 2>&1 || [ -t 0 ]; then HAVE_SUDO=1; fi
fi

# Run a command with root privileges, however this machine grants them.
run_root() {
    if   [ "$IS_ROOT"   -eq 1 ]; then "$@"
    elif [ "$HAVE_SUDO" -eq 1 ]; then sudo "$@"
    else return 1
    fi
}

case "$OS" in
Linux)
    NGINX_ETC="/etc/nginx"
    LOG_DIR="/var/log/nginx"
    DEFAULT_WEBROOT="/var/www/ail-website"

    HAVE_SYSTEMD=0
    if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
        HAVE_SYSTEMD=1
    fi

    install_packages() {
        command -v apt-get >/dev/null 2>&1 \
            || die "no apt-get on this machine — install these yourself and re-run: $*"
        run_root env DEBIAN_FRONTEND=noninteractive apt-get update -qq \
            || die "apt-get update needs root — re-run with sudo"
        run_root env DEBIAN_FRONTEND=noninteractive apt-get install -y "$@" >/dev/null \
            || die "apt-get install failed for: $*"
    }

    # Debian lays sites out as sites-available + a symlink in sites-enabled;
    # RPM-style images only have conf.d.
    choose_conf_path() {
        if [ -d "$NGINX_ETC/sites-available" ] \
            && grep -qE 'include[[:space:]]+[^;]*sites-enabled' "$NGINX_ETC/nginx.conf"; then
            CONF_PATH="$NGINX_ETC/sites-available/$CONF_NAME"
            ENABLE_LINK="$NGINX_ETC/sites-enabled/$CONF_NAME"
        elif [ -d "$NGINX_ETC/conf.d" ]; then
            CONF_PATH="$NGINX_ETC/conf.d/$CONF_NAME"
            ENABLE_LINK=""
        else
            die "no sites-available or conf.d under $NGINX_ETC — cannot place the vhost"
        fi
    }

    candidate_conf_paths() {
        printf '%s\n' \
            "$NGINX_ETC/sites-available/$CONF_NAME" \
            "$NGINX_ETC/sites-enabled/$CONF_NAME" \
            "$NGINX_ETC/conf.d/$CONF_NAME"
    }

    # The master runs as root here and the workers as www-data, so the config
    # test belongs to root too.
    nginx_test() { run_root nginx -t 2>&1; }

    # The pidfile first: it is what nginx itself writes, whereas the "nginx:
    # master" process title depends on argv rewriting (invisible under
    # emulation) and pgrep needs procps, which minimal images drop.
    service_running() {
        if [ "$HAVE_SYSTEMD" -eq 1 ]; then
            systemctl is-active --quiet nginx
        elif [ -s /run/nginx.pid ] && kill -0 "$(cat /run/nginx.pid)" 2>/dev/null; then
            return 0
        elif command -v pgrep >/dev/null 2>&1; then
            pgrep -f "nginx: master" >/dev/null 2>&1
        else
            return 1
        fi
    }

    service_reload() {
        if [ "$HAVE_SYSTEMD" -eq 1 ]; then run_root systemctl reload nginx >/dev/null 2>&1
        else run_root nginx -s reload >/dev/null 2>&1
        fi
    }

    service_start_at_boot() {
        if [ "$HAVE_SYSTEMD" -eq 1 ]; then
            run_root systemctl enable --now nginx >/dev/null 2>&1 \
                || die "could not enable the nginx service — re-run with sudo"
            ok "systemd: nginx enabled and running — it starts again at boot"
        elif run_root nginx 2>/dev/null; then
            warn "no systemd here, so nginx was started directly — nothing will restart it at boot"
        elif service_reload; then
            # It was already up; this machine just has no way to report that.
            ok "nginx was already running — reloaded it instead"
        else
            die "could not start nginx"
        fi
    }

    confirm_autostart() {
        if [ "$HAVE_SYSTEMD" -eq 1 ]; then
            if systemctl is-enabled --quiet nginx 2>/dev/null; then
                ok "auto-start registered: systemctl is-enabled nginx → enabled"
            else
                warn "nginx is NOT enabled at boot — fix with: systemctl enable nginx"
            fi
        fi
    }

    # Firewalls are the operator's call: report, never change.
    firewall_note() {
        local status=""
        if command -v ufw >/dev/null 2>&1; then
            status="$(run_root ufw status 2>/dev/null || true)"
            if printf '%s' "$status" | grep -q "Status: active" \
                && ! printf '%s' "$status" | grep -q "$PORT"; then
                warn "ufw is active with no rule for $PORT — allow it with: ufw allow ${PORT}/tcp"
            fi
        fi
    }
    ;;
Darwin)
    command -v brew >/dev/null 2>&1 || die "Homebrew is not installed — see https://brew.sh"
    BREW_PREFIX="$(brew --prefix)"
    NGINX_ETC="$BREW_PREFIX/etc/nginx"
    LOG_DIR="$BREW_PREFIX/var/log/nginx"
    DEFAULT_WEBROOT="$BREW_PREFIX/var/www/ail-website"

    install_packages() { brew install "$@"; }

    # Homebrew's servers/ is the canonical drop point but is root-owned on many
    # machines; fall back to a user-owned include dir when sudo cannot prompt,
    # so the dev machine still finishes without a password.
    choose_conf_path() {
        local servers="$NGINX_ETC/servers" fallback="$NGINX_ETC/ail-website.d"
        ENABLE_LINK=""
        if [ -d "$servers" ] && { [ -w "$servers" ] || [ "$IS_ROOT" -eq 1 ] || [ "$HAVE_SUDO" -eq 1 ]; }; then
            CONF_PATH="$servers/$CONF_NAME"
            return 0
        fi
        CONF_PATH="$fallback/$CONF_NAME"
        mkdir -p "$fallback"
        if ! grep -qF "ail-website.d/*.conf" "$NGINX_ETC/nginx.conf"; then
            [ -w "$NGINX_ETC/nginx.conf" ] || die "cannot write $servers (needs sudo) or $NGINX_ETC/nginx.conf"
            cp "$NGINX_ETC/nginx.conf" "$NGINX_ETC/nginx.conf.bak-ail"
            # Slip the include in beside the one Homebrew already ships.
            awk '{ print } /^[[:space:]]*include[[:space:]]+servers\/\*;/ { print "    include ail-website.d/*.conf;" }' \
                "$NGINX_ETC/nginx.conf.bak-ail" > "$NGINX_ETC/nginx.conf"
            grep -qF "ail-website.d/*.conf" "$NGINX_ETC/nginx.conf" \
                || die "could not add the include to nginx.conf — add 'include ail-website.d/*.conf;' inside http{} by hand"
        fi
        warn "$servers needs sudo; using $fallback instead"
    }

    candidate_conf_paths() {
        printf '%s\n' \
            "$NGINX_ETC/servers/$CONF_NAME" \
            "$NGINX_ETC/ail-website.d/$CONF_NAME"
    }

    # As this user, not root: the pidfile and logs belong to it, and a root
    # test would write root-owned logs the service can no longer append to.
    nginx_test() { nginx -t 2>&1; }

    service_running() { pgrep -f "nginx: master" >/dev/null 2>&1; }
    service_reload()  { nginx -s reload >/dev/null 2>&1; }

    service_start_at_boot() {
        brew services start nginx >/dev/null
        ok "nginx service started"
    }

    confirm_autostart() {
        # Ask brew where the plist is — it has renamed the label before
        # (homebrew.mxcl.nginx → sh.brew.nginx), so the path cannot be hardcoded.
        local plist
        plist="$(brew services list 2>/dev/null | awk '$1 == "nginx" { print $NF }')"
        case "$plist" in
            '~'/*) plist="$HOME/${plist#'~'/}" ;;
            /*)    ;;
            *)     plist="" ;;
        esac
        if [ -n "$plist" ] && [ -f "$plist" ] \
            && /usr/libexec/PlistBuddy -c 'Print :RunAtLoad' "$plist" 2>/dev/null | grep -qi true; then
            ok "auto-start registered: $plist (RunAtLoad, i.e. at login)"
        else
            warn "could not confirm auto-start — check 'brew services list' for nginx"
        fi
    }

    firewall_note() { :; }
    ;;
*)
    die "unsupported platform: $OS (this script handles Linux and macOS)"
    ;;
esac

# ------------------------------------------------------------- 1. toolchain --

say "Checking the toolchain ($OS)"

[ -f "$TEMPLATE" ] || die "missing config template: $TEMPLATE"

# curl verifies the deploy; rsync publishes it. Minimal server images have
# neither, so collect what is missing and install it alongside nginx.
WANTED=""
command -v nginx >/dev/null 2>&1 || WANTED="$WANTED nginx"
command -v curl  >/dev/null 2>&1 || WANTED="$WANTED curl"
command -v rsync >/dev/null 2>&1 || WANTED="$WANTED rsync"

if [ -n "$WANTED" ]; then
    say "Installing:$WANTED"
    # shellcheck disable=SC2086
    install_packages $WANTED
fi
command -v nginx >/dev/null 2>&1 || die "nginx is still not on PATH after installing"
command -v curl  >/dev/null 2>&1 || die "curl is required to verify the deploy"
ok "nginx $(nginx -v 2>&1 | sed 's|.*/||')"

[ -f "$NGINX_ETC/nginx.conf" ] || die "no nginx.conf under $NGINX_ETC"
run_root mkdir -p "$LOG_DIR" 2>/dev/null || mkdir -p "$LOG_DIR" 2>/dev/null || true

# ----------------------------------------------------------------- 2. build --

if [ "$SKIP_BUILD" -eq 1 ]; then
    [ -f "$REPO_ROOT/dist/index.html" ] || die "--skip-build was given but dist/index.html does not exist"
    ok "reusing the existing dist/"
else
    command -v npm >/dev/null 2>&1 \
        || die "npm is not on PATH — install Node.js, or build elsewhere, copy dist/ here and re-run with --skip-build"

    say "Building the site"
    cd "$REPO_ROOT"

    if [ ! -d node_modules ] || [ package-lock.json -nt node_modules ]; then
        npm ci
    else
        ok "dependencies already installed"
    fi

    if [ -n "$SITE_URL" ]; then
        VITE_SITE_URL="$SITE_URL" npm run build
    else
        npm run build
    fi

    [ -f "$REPO_ROOT/dist/index.html" ] && [ -f "$REPO_ROOT/dist/simulator/index.html" ] \
        || die "build finished but dist/ is missing an entry point"
    ok "built both pages into dist/"
fi

# --------------------------------------------------------------- 3. publish --

if [ "$IN_PLACE" -eq 1 ]; then
    WEBROOT="$REPO_ROOT/dist"
    case "$WEBROOT" in
        /Volumes/*|/media/*|/mnt/*) warn "serving from $WEBROOT — nginx will 404 whenever that volume is unmounted" ;;
    esac
    ok "serving dist/ in place: $WEBROOT"
else
    [ -n "$WEBROOT" ] || WEBROOT="$DEFAULT_WEBROOT"
    say "Publishing to $WEBROOT"

    # This publish deletes whatever it does not recognise. Refuse to point it
    # at a directory that is not already ours — another app's docroot must
    # never be emptied by a mistyped --webroot. A previous deploy is known by
    # its marker, or by carrying both of our entry points.
    if [ -d "$WEBROOT" ] && [ -n "$(ls -A "$WEBROOT" 2>/dev/null || true)" ] \
        && [ ! -f "$WEBROOT/.ail-website" ] \
        && { [ ! -f "$WEBROOT/index.html" ] || [ ! -f "$WEBROOT/simulator/index.html" ]; }; then
        die "$WEBROOT is not empty and was not published by this script — refusing to overwrite it"
    fi

    mkdir -p "$WEBROOT" 2>/dev/null || run_root mkdir -p "$WEBROOT" \
        || die "cannot create $WEBROOT — re-run with sudo"

    # Writing under /var/www usually needs root; under a brew prefix it does not.
    AS_ROOT=0
    [ -w "$WEBROOT" ] || AS_ROOT=1
    maybe_root() { if [ "$AS_ROOT" -eq 1 ]; then run_root "$@"; else "$@"; fi }

    printf 'published by scripts/deploy.sh\n' | maybe_root tee "$WEBROOT/.ail-website" >/dev/null

    # The marker is ours, not the build's, so it has to survive the sync.
    if command -v rsync >/dev/null 2>&1; then
        maybe_root rsync -a --delete --exclude='.ail-website' "$REPO_ROOT/dist/" "$WEBROOT/"
    else
        maybe_root find "$WEBROOT" -mindepth 1 -maxdepth 1 ! -name '.ail-website' -exec rm -rf {} +
        maybe_root cp -R "$REPO_ROOT/dist/." "$WEBROOT/"
    fi
    maybe_root chmod -R a+rX "$WEBROOT"
    ok "$(find "$WEBROOT" -type f ! -name '.ail-website' | wc -l | tr -d ' ') files published"
fi

# ---------------------------------------------------------------- 4. config --

say "Configuring nginx on port $PORT"

CONF_PATH=""
ENABLE_LINK=""
choose_conf_path

# Somebody else on this port is a hard stop — nginx would keep serving theirs
# and quietly ignore ours. Look at every config nginx actually loads (includes
# can point anywhere) plus everything staged under the config dir, and skip the
# files this script generated, whatever they are called or symlinked as.
CONF_LIST="$( { { nginx -T 2>/dev/null || true; } | sed -n 's/^# configuration file \(.*\):$/\1/p'
                find "$NGINX_ETC" -type f 2>/dev/null || true; } | sed '/^$/d' | sort -u)"
OTHER_CONF=""
if [ -n "$CONF_LIST" ]; then
    while IFS= read -r conf; do
        [ -f "$conf" ] || continue
        if ! grep -qE "listen[[:space:]]+(\[?[0-9a-f.:]+\]?:)?${PORT}[;[:space:]]" "$conf" 2>/dev/null; then continue; fi
        if grep -qF "$GEN_MARKER" "$conf" 2>/dev/null; then continue; fi
        OTHER_CONF="$OTHER_CONF  $conf"$'\n'
    done <<< "$CONF_LIST"
fi
[ -z "$OTHER_CONF" ] || die "another nginx config already claims port $PORT:
$OTHER_CONF"

HOLDER=""
if command -v lsof >/dev/null 2>&1; then
    HOLDER="$( { lsof -nP -iTCP:"$PORT" -sTCP:LISTEN 2>/dev/null || true; } | awk 'NR>1 {print $1}' | sort -u | tr '\n' ' ')"
elif command -v ss >/dev/null 2>&1; then
    HOLDER="$( { ss -H -ltnp "sport = :$PORT" 2>/dev/null || true; } | sed -n 's/.*users:((\"\([^"]*\)\".*/\1/p' | sort -u | tr '\n' ' ')"
fi
case "${HOLDER// /}" in
    ''|nginx) ;;
    *) die "port $PORT is already held by: ${HOLDER}— stop it or pass --port" ;;
esac

RENDERED="$(mktemp "${TMPDIR:-/tmp}/ail-website-conf.XXXXXX")"
BACKUP=""
trap 'rm -f "$RENDERED" "$BACKUP"' EXIT

{
    echo "$GEN_MARKER from deploy/nginx/ail-website.conf."
    echo "# Every deploy overwrites this file — edit the one in the repo instead."
    sed \
        -e "s|^.*# @@PORT@@$|    listen      ${PORT};|" \
        -e "s|^.*# @@PORT6@@$|    listen      [::]:${PORT};|" \
        -e "s|^.*# @@ROOT@@$|    root        ${WEBROOT};|" \
        -e "s|^.*# @@ACCESS_LOG@@$|    access_log  ${LOG_DIR}/ail-website.access.log;|" \
        -e "s|^.*# @@ERROR_LOG@@$|    error_log   ${LOG_DIR}/ail-website.error.log;|" \
        "$TEMPLATE"
} > "$RENDERED"

! grep -q '@@' "$RENDERED" || die "a @@TOKEN@@ survived rendering — template and script have drifted"

# Keep the old config so a failed `nginx -t` can be rolled straight back.
if [ -f "$CONF_PATH" ]; then
    BACKUP="$(mktemp "${TMPDIR:-/tmp}/ail-website-prev.XXXXXX")"
    cat "$CONF_PATH" > "$BACKUP"
fi

install_conf() {
    if [ -w "$(dirname "$CONF_PATH")" ] && { [ ! -e "$CONF_PATH" ] || [ -w "$CONF_PATH" ]; }; then
        install -m 0644 "$1" "$CONF_PATH"
    else
        run_root install -m 0644 "$1" "$CONF_PATH" \
            || die "cannot write $CONF_PATH — re-run with sudo"
    fi
}

install_conf "$RENDERED"
if [ -n "$ENABLE_LINK" ]; then
    run_root ln -sfn "$CONF_PATH" "$ENABLE_LINK" 2>/dev/null \
        || ln -sfn "$CONF_PATH" "$ENABLE_LINK" \
        || die "cannot enable the site at $ENABLE_LINK"
    ok "config installed at $CONF_PATH (enabled via $ENABLE_LINK)"
else
    ok "config installed at $CONF_PATH"
fi

restore_conf() {
    if [ -n "$BACKUP" ]; then
        install_conf "$BACKUP"
    else
        rm -f "$CONF_PATH" 2>/dev/null || run_root rm -f "$CONF_PATH" || true
        [ -z "$ENABLE_LINK" ] || rm -f "$ENABLE_LINK" 2>/dev/null || run_root rm -f "$ENABLE_LINK" || true
    fi
}

if ! TEST_OUT="$(nginx_test)"; then
    restore_conf
    printf '%s\n' "$TEST_OUT" >&2
    die "nginx rejected the config — the previous one has been put back"
fi
rm -f "$BACKUP"; BACKUP=""
ok "nginx -t passed"

# Only once the new config has passed: drop any copy of ours left behind in
# another candidate location, or two server blocks fight over the same port.
# This has to come after the test — deleting it earlier would mean a rejected
# config takes the site down with it, having removed the one that was serving.
while IFS= read -r stale; do
    if [ "$stale" = "$CONF_PATH" ] || [ "$stale" = "$ENABLE_LINK" ]; then continue; fi
    if [ ! -e "$stale" ] && [ ! -L "$stale" ]; then continue; fi
    rm -f "$stale" 2>/dev/null || run_root rm -f "$stale" \
        || die "a stale copy of this config needs root to remove: rm $stale"
    warn "removed a stale copy at $stale"
    nginx_test >/dev/null || die "nginx rejected the config after removing $stale"
done <<< "$(candidate_conf_paths)"

# --------------------------------------------------------------- 5. service --

if [ "$NO_SERVICE" -eq 1 ]; then
    warn "--no-service: the service manager was left alone"
    if service_reload; then ok "reloaded the running nginx"; else warn "nginx is not running"; fi
elif service_running; then
    # This nginx may already be serving other people's sites. A reload is
    # graceful — old workers finish their requests — so never restart the
    # master out from under them, even if the reload fails.
    if service_reload; then
        ok "reloaded the running nginx — every other vhost kept serving"
    else
        warn "nginx is running but refused the reload; apply it yourself with:"
        warn "    systemctl restart nginx   # or: brew services restart nginx"
        warn "    (this briefly interrupts every site on this nginx)"
    fi
    confirm_autostart
else
    say "Starting nginx and enabling it at boot"
    service_start_at_boot
    confirm_autostart
fi

# ---------------------------------------------------------------- 6. verify --

say "Verifying http://localhost:$PORT"

reachable() { curl -s -o /dev/null --max-time 3 "http://127.0.0.1:$PORT/" 2>/dev/null; }
for _ in $(seq 1 30); do
    if reachable; then break; fi
    sleep 0.2
done

code() { curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:$PORT$1"; }
FAILED=0
check() {
    local path="$1" want="$2" got
    got="$(code "$path")"
    if [ "$got" = "$want" ]; then ok "$path → $got"
    else warn "$path → $got (expected $want)"; FAILED=1; fi
}

check /                                200
check /simulator/                      200
check /og.png                          200
check /this-path-does-not-exist        404

[ "$FAILED" -eq 0 ] || die "nginx is configured but is not serving as expected — see $LOG_DIR/ail-website.error.log"

firewall_note

# Everything else this nginx serves, so the blast radius of a deploy is visible.
OTHER_LISTENS="$( { nginx -T 2>/dev/null || run_root nginx -T 2>/dev/null || true; } \
    | sed -n 's/^[[:space:]]*listen[[:space:]]\{1,\}\([^;]*\);.*/\1/p' \
    | sort -u | { grep -vxE "(\[::\]:)?${PORT}" || true; } | tr '\n' ' ')"

cat <<SUMMARY

  site        http://localhost:$PORT/
  simulator   http://localhost:$PORT/simulator/

  webroot     $WEBROOT
  config      $CONF_PATH
  untouched   ${OTHER_LISTENS:-none} (other vhosts on this nginx)
  logs        $LOG_DIR/ail-website.{access,error}.log

  Re-run this script after any change to publish it.
SUMMARY

if [ "$OS" = "Linux" ]; then
    cat <<'CLOUD'
  On a cloud VM the provider firewall (GCP VPC rule, AWS security group) has to
  allow the port as well — a host firewall rule alone is not enough.

CLOUD
fi
